-- ReadableCode (លេខសំគាល់) becomes a system-issued client number: C00001,
-- C00002, … Staff no longer type it, and it cannot be edited afterwards.
--
-- Generated by a sequence used as a column DEFAULT rather than in application
-- code. Reading the current maximum and adding one races: two registrations
-- submitted at the same moment would read the same maximum and claim the same
-- number. nextval() is atomic and never returns a value twice, even under
-- concurrent inserts or rollback.

CREATE SEQUENCE IF NOT EXISTS "client_readable_code_seq";

-- The unique index below would fail on existing duplicates with an error that
-- does not say how many there are. Report first, change nothing.
DO $$
DECLARE dupes integer;
BEGIN
  SELECT count(*) INTO dupes FROM (
    SELECT "ReadableCode"
      FROM "Client_PersonalInformation"
     WHERE "ReadableCode" IS NOT NULL AND btrim("ReadableCode") <> ''
     GROUP BY "ReadableCode"
    HAVING count(*) > 1
  ) d;

  IF dupes > 0 THEN
    RAISE EXCEPTION
      'ReadableCode: % value(s) appear on more than one client. Make them unique before this column becomes an identifier; nothing has been changed.', dupes;
  END IF;
END $$;

-- Continue past anything already shaped like C00001 so issued numbers are never
-- reused. Codes in any other shape are left alone and simply not counted.
SELECT setval(
  'client_readable_code_seq',
  COALESCE(
    (SELECT MAX(substring("ReadableCode" from '^C([0-9]+)$')::bigint)
       FROM "Client_PersonalInformation"
      WHERE "ReadableCode" ~ '^C[0-9]+$'),
    0
  ) + 1,
  false
);

ALTER TABLE "Client_PersonalInformation"
  ALTER COLUMN "ReadableCode"
  SET DEFAULT ('C' || lpad(nextval('client_readable_code_seq')::text, 5, '0'));

CREATE UNIQUE INDEX "Client_PersonalInformation_ReadableCode_key"
  ON "Client_PersonalInformation" ("ReadableCode");
